Repository COSC481W-2021Winter/capstone-project-mohcamanagement, pull requests merged in 2021-03, with the labels that each got.

#43 Implemented add item to inventoryLog page
  src/pages/inventoryLog.php
  vendor/codeception/module-db/.github/workflows/main.yml
  vendor/codeception/module-db/LICENSE
  vendor/codeception/module-db/composer.json
  vendor/codeception/module-db/src/Codeception/Lib/DbPopulator.php
  vendor/codeception/module-db/src/Codeception/Lib/Driver/Db.php
  vendor/codeception/module-db/src/Codeception/Lib/Driver/MySql.php
  vendor/codeception/module-db/src/Codeception/Lib/Driver/Oci.php
  vendor/codeception/module-db/src/Codeception/Lib/Driver/PostgreSql.php
  vendor/codeception/module-db/src/Codeception/Lib/Driver/SqlSrv.php
  vendor/codeception/module-db/src/Codeception/Lib/Driver/Sqlite.php
  vendor/codeception/module-db/src/Codeception/Lib/Interfaces/Db.php
  vendor/codeception/module-db/src/Codeception/Module/Db.php
Labels: Sprint_1

#50 DKilroy Refactoring for Sprint 1
  resources/OverseerLogo.png
  resources/OverseerTransparent.png
  src/pages/adminCreateUser.php
  src/pages/adminMain.php
  src/pages/companyRegister.php
  src/pages/inventoryLog.php
  src/pages/inventoryOrder.php
  src/pages/login.php
  src/pages/scheduleGeneration.php
  src/pages/userCheck.php
  src/pages/userMain.php
  src/pages/userRequestOff.php
  src/pages/userUpdateAvailabilty.php
Labels: Maintenance, Sprint_1

#56 Populated the table with initial values of 0 for inventory log, Also …
  src/pages/inventoryLog.php
  src/pages/inventoryOrder.php
Labels: Sprint_1.5, bug

#52 Tests for Inventory Log Page
  src/pages/inventoryLog.php
  tests/acceptance/inventoryLogCest.php
Labels: Sprint_1.5, Tests

#58 Fixed a typo in InventoryLogCest.php
  tests/acceptance/inventoryLogCest.php
Labels: Sprint_1.5, Tests

#69 HOTFIX adminCreateUser page
  src/pages/adminCreateUser.php
Labels: Maintenance, bug

#85 Stylesheet Bug
  src/pages/adminCreateUser.php
  src/pages/adminCreation.php
  src/pages/adminEditSchedule.php
  src/pages/adminMain.php
  src/pages/adminUpdateScedule.php
  src/pages/companyRegister.php
  src/pages/inventoryLog.php
  src/pages/inventoryOrder.php
  src/pages/login.php
  src/pages/scheduleGeneration.php
  src/pages/userCheck.php
  src/pages/userMain.php
  src/pages/userRequestOff.php
  src/pages/userUpdateAvailabilty.php
  src/style/style.css
Labels: Sprint 2.5, bug

#87 Tests for userRequestOff.php - invalid date testing
  src/pages/userRequestOff.php
  tests/acceptance/userRequestOffCest.php
Labels: Sprint 2.5, Tests

#92 Regex for the user creation pages
  src/pages/adminCreateUser.php
  src/pages/adminCreation.php
Labels: Maintenance, Sprint 2.5
